name: "PR Build and Test"
on:
  pull_request:

jobs:
  build-and-test:
    if: ${{ !startsWith(github.head_ref, 'changeset-release/') }}
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          package-manager-cache: false

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - name: Build
        run: yarn build

      - name: Run coverage
        run: yarn test:coverage

      # Remove node_modules to see if this action runs entirely compiled
      - name: Remove node_modules
        run: rm -rf node_modules

      - name: PR Test Reports
        uses: hyperse-io/vitest-coverage-reporter@v1.0.13
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          include-all-projects: "false"
          name: "PR Test Reports"
